%YAML 1.2
---
base_dir: data/
dataset_dir: "data/{x}/"
raw_dir: "data/{x}/raw/"
valid_dir: "data/{x}/validation/"
ingested_dir: "data/{x}/ingested/"
metadata_dir: "data/{x}/metadata/"
datasets:
  yellow_taxi:
    dataset_type: Tabular
    tables:
      yellow_taxi:
        url: "https://nyc-tlc.s3.amazonaws.com/trip+data/yellow_tripdata_{x}.csv"
        pattern: yellow_tripdata_{x}
        file_type: csv
        update: append
        include_columns: [tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount]
        default_ingestion: 2021-07
        ingestions:
    #      - 2010-07
          - 2020-01
          - 2020-02
          - 2020-03
          - 2020-04
          - 2020-05
          - 2020-06
          - 2020-07
          - 2020-08
          - 2020-09
          - 2020-10
          - 2020-11
          - 2020-12
          - 2021-01
          - 2021-02
          - 2021-03
          - 2021-04
          - 2021-05
          - 2021-06
          - 2021-07
          - 2021-07.test
      taxi_zones:
        url: "https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_{x}.csv"
        pattern: taxi+_zone_{x}
        file_type: csv
        default_ingestion: lookup
        uppdate: replace
        ingestions:
          - lookup
  citibike:
    dataset_type: Tabular
    tables:
      citibike:
        url: https://nyc-tlc.s3.amazonaws.com/trip+data/{x}-citibike-tripdata.csv
        pattern: "{x}-citibike-tripdata"
        file_type: csv
        update: append
        default_ingestion: "202107"
        ingestions:
          - 202107
  flight_radar24:
    dataset_type: Tabular
    tables:
      flight_radar24:
        url: "https://nyc-tlc.s3.amazonaws.com/trip+data/flight_radar24_{x}.csv"
        pattern: flight_radar24_{x}
        file_type: csv
        update: append
        default_ingestion: all
        ingestions:
          - all
          - 2022-01
          - 2022-02
          - 2022-03
          - 2022-04
  intuizi:
    dataset_type: Tabular
    tables:
      intuizi:
        url: https://us-east-1.console.aws.amazon.com/s3/buckets/intuizi-external/test_{x}.csv
        pattern: test_{x}.csv
        file_type: csv
        update: append
        default_ingestion: test5
        ingestions:
          - test3
          - test4
          - test5
  techselerator:
    dataset_type: Tabular
    tables:
      techselerator:
        url: https://us-east-1.console.aws.amazon.com/s3/buckets/intuizi-external/Neom_UK_Extract_{x}_UTF_8.csv
        pattern: test_{x}.csv
        file_type: csv
        update: append
        default_ingestion: test5
        ingestions:
          - test3
          - test4
          - test5
  custom_weather:
    dataset_type: Tabular
    tables:
      locations:
        url: https://somwebsite.or.other/some/path/locations{x}.csv
        pattern: locations{x}.csv
        file_type: csv
        delimiter: "|"
        update: replace
        column_names: [station_id, station_name, region_code, country_ISO2, latitude, longitude, timezone, altitude, nothing]
        include_columns: [station_id, station_name, region_code, country_ISO2, latitude, longitude, timezone, altitude]
        column_types:
          altitude: int16
        safe: False
        default_ingestion: ""
        ingestions:
          - ""
      weather:
        url: https://somwebsite.or.other/some/path/weather.{x}.csv
        pattern: weather.{x}.csv
        file_type: 'csv'
        delimeter: "|"
        null_values: ["*"]
        timestamp_parsers: ["%Y%m%d%H%M"]
        update: append
        default_ingestion: 2022.05
        ingestions:
          - 2022.01
          - 2022.02
          - 2022.03
          - 2022.04
          - 2022.05
          - 2022.06
